name: Second Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: print greeting
        run: print("Hello World")
      - name: print goodbye
        run: echo "Done-bye"
        