name: Deploy to Amazon ECSs

on:
  push:
    branches: [ "main" ]


permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAR4HMVUUYTGGLWCHE
        aws-secret-access-key: 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
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: build
      run: docker build -t terraform .
    - name: tag
      run: docker tag terraform:latest 129345365297.dkr.ecr.us-east-1.amazonaws.com/terraform:latest
    - name: push
      run: docker push 129345365297.dkr.ecr.us-east-1.amazonaws.com/terraform:latest   
    - name: pull
      run: docker pull 129345365297.dkr.ecr.us-east-1.amazonaws.com/terraform:latest  
    - name: run
      run: docker run 129345365297.dkr.ecr.us-east-1.amazonaws.com/terraform@sha256:e1971fca854b7f71f2f0a9f88d5e5041ba722d278d1077d0db828df748e0f882
 
   

  
