name: Deploy to Amazon ECSs

on: workflow_dispatch
  
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAR4HMVUUY3Y6UQJ3L
        aws-secret-access-key: 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
        aws-region: us-east-1
        
    - name: Now We Intializing terraform
      run: terraform init
    - name: plan
      run: terraform plan
    - name: Building terraform
      run: terraform apply -auto-approve
    - name: Login to Amazon ECR
      id: Login-ECR
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build
      run: docker build -t terraform .
    - name: Tag
      run: docker tag terraform:latest 129345365297.dkr.ecr.us-east-1.amazonaws.com/terraform:latest
    - name: Push
      run: docker push 129345365297.dkr.ecr.us-east-1.amazonaws.com/terraform:latest      
 
